name: "🧩 Pull Request"
description: "Запрос на внесение изменений."
title: ""
# Можно настроить дефолтные метки/ассайни при желании:
# labels: ["needs review"]
# assignees: ["alyreniko"]
body:
  - type: markdown
    attributes:
      value: |
        Спасибо за вклад! Пожалуйста, заполните пункты ниже, чтобы ревью прошло быстрее.

  - type: checkboxes
    id: change-type
    attributes:
      label: "✨ Тип изменений"
      description: "Выбери одно или несколько"
      options:
        - label: "`feat` — новая функциональность"
        - label: "`fix` — исправление ошибок"
        - label: "`docs` — изменение документации"
        - label: "`style` — визуальные / форматирующие правки"
        - label: "`refactor` — улучшение структуры кода"
        - label: "`perf` — оптимизация производительности"
        - label: "`test` — добавлены / изменены тесты"
        - label: "`chore` — обновление зависимостей, конфигов и т.д."

  - type: textarea
    id: summary
    attributes:
      label: "📋 Описание"
      description: "Кратко: что сделано и зачем. Укажи, если были визуальные изменения (можно приложить скриншоты)."
      placeholder: "Добавлен компонент `HeroSection`, реализован адаптив под мобильные устройства."
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: "🧠 Причина изменений"
      description: "Почему эти изменения важны? Багфикс, фича, улучшение UX и т.д."
    validations:
      required: true

  - type: checkboxes
    id: tested
    attributes:
      label: "🧪 Проверено"
      options:
        - label: "Локально запущено и проверено"
        - label: "Проверен адаптив"
        - label: "Нет ошибок в консоли"
        - label: "Проверен деплой / билд"
        - label: "Код соответствует ESLint / Prettier"

  - type: textarea
    id: extra
    attributes:
      label: "🧷 Дополнительно"
      description: "Доп. комментарии, TODO или планы"
    validations:
      required: false

  - type: input
    id: figma
    attributes:
      label: "🔗 Figma / Дизайн-ссылка"
      placeholder: "https://www.figma.com/file/..."
    validations:
      required: false

  - type: input
    id: issue_link
    attributes:
      label: "🐞 Связанная задача (Issue)"
      placeholder: "Например: Closes #123"
    validations:
      required: false
