blank_issues_enabled: false

contact_links:
  - name: "💬 Обратная связь"
    url: "https://alyreniko.github.io/#contact"
    about: "Используй форму на сайте, если хочешь просто связаться или написать сообщение."
