name: "✨ Feature Request"
description: "Предложить новую идею, улучшение или компонент"
title: "feat: "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Спасибо за идею! Помогите понять ценность и контекст вашего предложения.

  - type: textarea
    id: idea
    attributes:
      label: "💡 Идея"
      description: "Кратко опишите предлагаемую возможность и зачем она нужна."
      placeholder: "Добавить секцию «Отзывы» на главную с анимацией появления карточек."
    validations:
      required: true

  - type: textarea
    id: value
    attributes:
      label: "🧩 Польза"
      description: "Как это улучшит сайт или UX? Кто будет использовать? Что изменится?"
      placeholder: "Интерфейс станет намного понятнее, пользователям будет проще ориентироваться"
    validations:
      required: true

  - type: textarea
    id: inspiration
    attributes:
      label: "🎨 Пример или вдохновение"
      description: "Ссылки на дизайн, сайты или примеры реализации (опционально)."
      placeholder: |
        🔗 Figma: https://www.figma.com/file/...
        🌐 Пример: https://example.com/
    validations:
      required: false

  - type: textarea
    id: implementation
    attributes:
      label: "⚙️ Возможная реализация"
      description: "Технический подход, компоненты или файлы. Можно добавить TODO-пункты."
      placeholder: |
        - Создать компонент `TestimonialsSection.vue`
        - Добавить JSON с отзывами
        - Подключить анимацию появления
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: "🕓 Приоритет"
      options:
        - "🟩 Низкий"
        - "🟨 Средний"
        - "🟥 Высокий"
      default: 1
    validations:
      required: true
